// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/12/2025, 6:28:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/layouts/**/*.{vue,js,mjs}","/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/composables/**/*.{js,ts,mjs}","/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/utils/**/*.{js,ts,mjs}","/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/pages/**/*.{vue,js,mjs}","/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/{A,a}pp.{vue,js,mjs}","/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/{E,e}rror.{vue,js,mjs}","/Users/janroe.cordero/Developer/nuxt-mastery/nuxtbnb/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;